"""
Generates notebooks/kaggle/train_deberta_kaggle.ipynb by embedding the
CURRENT contents of src/metrics.py, src/data.py, src/model.py, src/train.py
as %%writefile cells, plus a Kaggle-specific config.yaml (absolute
/kaggle/... paths; every hyperparameter identical to config/config.yaml).

Re-run this any time the src/ files change, so the Kaggle notebook never
drifts from what was actually developed and unit-tested locally:

    python scripts/gen_kaggle_notebook.py
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "src"
OUT = ROOT / "notebooks" / "kaggle" / "train_deberta_kaggle.ipynb"


def read(name: str) -> str:
    return (SRC / name).read_text(encoding="utf-8")


def code_cell(src: str) -> dict:
    return {
        "cell_type": "code",
        "metadata": {},
        "execution_count": None,
        "outputs": [],
        "source": src.splitlines(keepends=True),
    }


def md_cell(src: str) -> dict:
    return {"cell_type": "markdown", "metadata": {}, "source": src.splitlines(keepends=True)}


def writefile_cell(filename: str, content: str) -> dict:
    return code_cell(f"%%writefile {filename}\n" + content)


KAGGLE_CONFIG = """seed: 42

paths:
  raw_train_csv: /kaggle/input/competitions/jigsaw-unintended-bias-in-toxicity-classification/train.csv
  raw_test_csv: /kaggle/input/competitions/jigsaw-unintended-bias-in-toxicity-classification/test.csv
  processed_dir: /kaggle/working/data/processed
  model_dir: /kaggle/working/models
  reports_dir: /kaggle/working/reports
  figures_dir: /kaggle/working/reports/figures

data:
  val_size: 0.05
  dev_subsample_size: 200000
  min_per_subgroup_dev: 500
  toxic_threshold: 0.5
  identity_threshold: 0.5

identity_columns:
  - male
  - female
  - homosexual_gay_or_lesbian
  - christian
  - jewish
  - muslim
  - black
  - white
  - psychiatric_or_mental_illness

aux_columns:
  - severe_toxicity
  - obscene
  - threat
  - insult
  - identity_attack
  - sexual_explicit

transformer:
  model_name: microsoft/deberta-v3-base
  max_len: 220
  batch_size: 32
  eval_batch_size: 64
  lr: 2.0e-5
  warmup_ratio: 0.05
  epochs: 1   # 1-2 is the spec's range; start with 1 for a faster real
              # result (~3.5-4.5h vs ~7-9h) -- bump to 2 for a rerun if
              # time/GPU-quota allows once this arm's numbers are in.
  weight_decay: 0.01
  fp16: true
  aux_loss_weight: 0.25
  use_multitask_heads: true   # flip to false + rerun for the ablation
  weighting_scheme: metric_derived   # none | inverse_frequency | metric_derived -- flip for the ablation table
  grad_accum_steps: 1
  max_grad_norm: 1.0
  log_every: 100
  checkpoint_every_steps: 3000   # overwrites a single _latest.pt -- see src/train.py
"""


def build_notebook() -> dict:
    cells = [
        md_cell(
"""# DeBERTa-v3 multi-task toxicity fine-tune -- Kaggle Notebook

Runs the exact same `src/` code developed and unit-tested locally
(this notebook just re-materializes those files here via `%%writefile`,
generated by `scripts/gen_kaggle_notebook.py` -- do not hand-edit the
code cells below, regenerate instead so this never drifts from what was
actually tested).

**Before running:**
1. Settings (right panel) -> Accelerator -> **GPU T4 x2** or **P100**.
2. Add data -> search **"Jigsaw Unintended Bias in Toxicity Classification"**
   -> Add. This mounts the competition files under
   `/kaggle/input/jigsaw-unintended-bias-in-toxicity-classification/`.
3. Settings -> Internet -> **On** (needed to download `deberta-v3-base`
   weights from Hugging Face on first run).
4. Session length: full-data training is ~3.5-4.5h/epoch x 2 epochs on a
   T4 -- comfortably inside a 9h session, but checkpoints are written
   every 2000 steps to `/kaggle/working/models/` in case of a disconnect.

**To run the ablations referenced in the README:** edit `config.yaml`
below (the `%%writefile config.yaml` cell) -- flip `use_multitask_heads`
and/or `weighting_scheme`, re-run that cell + the training cell, save a
new notebook version per configuration so each run's output is preserved.
"""
        ),
        md_cell(
            "## 1. Install extra dependencies\n\n"
            "`torch`/`transformers` ship preinstalled on Kaggle GPU notebooks. "
            "The preinstalled torch build (observed: 2.10.0+cu128) has dropped "
            "kernel support for Pascal-generation GPUs (sm_60, e.g. the P100 "
            "Kaggle sometimes assigns) -- confirmed the hard way: `CUDA error: "
            "no kernel image is available for execution on the device`, right "
            "after `torch.zeros(..., device='cuda')`. `machine_shape` in "
            "kernel-metadata.json did not reliably control which GPU an "
            "API-pushed kernel gets, so instead of gambling on GPU assignment, "
            "we detect the actual device's compute capability and reinstall a "
            "torch/cu121 build (still spans Pascal through Hopper) only if the "
            "preinstalled one can't run a kernel on this GPU."
        ),
        code_cell("!pip install -q sentencepiece pyyaml\n"),
        code_cell(
            "import subprocess\n"
            "import torch\n"
            "\n"
            "def cuda_actually_works() -> bool:\n"
            "    if not torch.cuda.is_available():\n"
            "        return False\n"
            "    try:\n"
            "        x = torch.zeros(4, device='cuda')\n"
            "        _ = x + 1\n"
            "        torch.cuda.synchronize()\n"
            "        return True\n"
            "    except Exception as e:\n"
            "        print(f'CUDA smoke op failed on preinstalled torch: {e}')\n"
            "        return False\n"
            "\n"
            "print('torch', torch.__version__, 'cuda build', torch.version.cuda)\n"
            "if torch.cuda.is_available():\n"
            "    print('device:', torch.cuda.get_device_name(0), torch.cuda.get_device_capability(0))\n"
            "\n"
            "if not cuda_actually_works():\n"
            "    print('Reinstalling a broader-compatibility torch build (cu121)...')\n"
            "    subprocess.run(\n"
            "        ['pip', 'install', '-q', '--force-reinstall',\n"
            "         'torch==2.4.1', '--index-url', 'https://download.pytorch.org/whl/cu121'],\n"
            "        check=True,\n"
            "    )\n"
            "    # We don't use torchvision/torchaudio anywhere -- but they stay\n"
            "    # pinned to the OLD torch build's version after the line above,\n"
            "    # which breaks their compiled ops (torchvision::nms) against the\n"
            "    # new torch, which in turn breaks transformers' DebertaV2Model\n"
            "    # import (it probes torchvision at import time). Simplest fix:\n"
            "    # remove what we don't need instead of chasing matched versions.\n"
            "    subprocess.run(['pip', 'uninstall', '-y', '-q', 'torchvision', 'torchaudio'], check=True)\n"
            "    # Verify via a FRESH subprocess, not this kernel's already-imported\n"
            "    # torch module -- Python cannot cleanly reload a C-extension\n"
            "    # module in-process, but train.py runs as its own subprocess\n"
            "    # later anyway and will import the newly installed package fine\n"
            "    # regardless of what this cell's `torch` object thinks.\n"
            "    check = subprocess.run(\n"
            "        ['python', '-c',\n"
            "         \"import torch; x=torch.zeros(4, device='cuda'); y=x+1; torch.cuda.synchronize(); \"\n"
            "         \"print('torch', torch.__version__, 'cuda build', torch.version.cuda); print('CUDA OK:', y)\"],\n"
            "    )\n"
            "    assert check.returncode == 0, 'CUDA still broken after torch reinstall -- needs manual investigation.'\n"
            "else:\n"
            "    print('Preinstalled torch already works on this GPU -- no reinstall needed.')\n"
        ),
        code_cell(
            "import os\n"
            "# Sanity check the data mount before spending any GPU time on it --\n"
            "# API-pushed kernels mount competition data at\n"
            "# /kaggle/input/competitions/<slug>/, NOT /kaggle/input/<slug>/ like\n"
            "# the browser 'Add Data' flow does. Confirmed the hard way once.\n"
            "for root, _, files in os.walk('/kaggle/input'):\n"
            "    for f in files:\n"
            "        print(os.path.join(root, f))\n"
        ),
        md_cell(
            "## 2. Materialize the project's src/ modules\n\n"
            "Identical content to the local repo's `src/metrics.py`, `src/data.py`, "
            "`src/model.py`, `src/train.py` -- see that repo for the documented "
            "rationale behind each design choice (bias metric derivation, "
            "weighting scheme, multi-task heads)."
        ),
        writefile_cell("metrics.py", read("metrics.py")),
        writefile_cell("data.py", read("data.py")),
        writefile_cell("model.py", read("model.py")),
        writefile_cell("train.py", read("train.py")),
        md_cell(
            "## 3. Kaggle-specific config\n\n"
            "Same hyperparameters as `config/config.yaml` in the repo; only the "
            "paths differ (point at `/kaggle/input/...` and write outputs under "
            "`/kaggle/working/`)."
        ),
        writefile_cell("config.yaml", KAGGLE_CONFIG),
        md_cell(
            "## 4. Smoke test (structural, ~1-2 min)\n\n"
            "Runs the full loop end-to-end on 300 rows before committing to a "
            "multi-hour run -- catches config/schema mistakes cheaply. Uses "
            "`subprocess` + a raised exception (not a bare `!` shell call) "
            "specifically so a failure here **halts the notebook** instead of "
            "silently falling through to the multi-hour cell below -- a bare "
            "`!python ...` returning nonzero does not stop batch execution on "
            "its own, which would otherwise burn GPU quota on a broken run."
        ),
        code_cell(
            "import subprocess\n"
            "r = subprocess.run(['python', 'train.py', '--config', 'config.yaml', "
            "'--sample', '300', '--out-name', 'smoketest'])\n"
            "if r.returncode != 0:\n"
            "    raise RuntimeError('Smoke test failed (see output above) -- aborting before the full run.')\n"
            "print('SMOKE TEST PASSED')\n"
        ),
        md_cell(
            "## 5. Full training run\n\n"
            "This is the multi-hour cell. Metrics (overall AUC + the three bias "
            "power-means) print after every epoch; the final state_dict is saved "
            "to `/kaggle/working/models/deberta_multitask_final.pt` -- download "
            "it from the notebook's Output tab, or add `/kaggle/working` as a new "
            "Kaggle Dataset from the notebook's \"Save Version\" flow so it "
            "persists past the session."
        ),
        code_cell(
            "import subprocess\n"
            "r = subprocess.run(['python', 'train.py', '--config', 'config.yaml', "
            "'--out-name', 'deberta_multitask'])\n"
            "if r.returncode != 0:\n"
            "    raise RuntimeError('Training run failed (see output above).')\n"
            "print('TRAINING RUN COMPLETE')\n"
        ),
        md_cell(
            "## 6. Copy results back into the local repo\n\n"
            "After downloading `/kaggle/working/reports/*.csv` from the Output "
            "tab, drop them into `reports/` locally and update the README's "
            "result tables + `reports/results.md` log."
        ),
    ]

    return {
        "cells": cells,
        "metadata": {
            "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
            "language_info": {"name": "python", "version": "3.10"},
            "accelerator": "GPU",
        },
        "nbformat": 4,
        "nbformat_minor": 5,
    }


if __name__ == "__main__":
    nb = build_notebook()
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(nb, indent=1), encoding="utf-8")
    print(f"wrote {OUT} ({len(nb['cells'])} cells)")
