"""
Generates notebooks/kaggle/train_deberta_kaggle.ipynb by embedding the
CURRENT contents of src/metrics.py, src/data.py, src/model.py, src/train.py
as %%writefile cells, plus a Kaggle-specific config.yaml (absolute
/kaggle/... paths; every hyperparameter identical to config/config.yaml).

Re-run this any time the src/ files change, so the Kaggle notebook never
drifts from what was actually developed and unit-tested locally:

    python scripts/gen_kaggle_notebook.py
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "src"
OUT = ROOT / "notebooks" / "kaggle" / "train_deberta_kaggle.ipynb"


def read(name: str) -> str:
    return (SRC / name).read_text(encoding="utf-8")


def code_cell(src: str) -> dict:
    return {
        "cell_type": "code",
        "metadata": {},
        "execution_count": None,
        "outputs": [],
        "source": src.splitlines(keepends=True),
    }


def md_cell(src: str) -> dict:
    return {"cell_type": "markdown", "metadata": {}, "source": src.splitlines(keepends=True)}


def writefile_cell(filename: str, content: str) -> dict:
    return code_cell(f"%%writefile {filename}\n" + content)


KAGGLE_CONFIG = """seed: 42

paths:
  raw_train_csv: /kaggle/input/jigsaw-unintended-bias-in-toxicity-classification/train.csv
  raw_test_csv: /kaggle/input/jigsaw-unintended-bias-in-toxicity-classification/test.csv
  processed_dir: /kaggle/working/data/processed
  model_dir: /kaggle/working/models
  reports_dir: /kaggle/working/reports
  figures_dir: /kaggle/working/reports/figures

data:
  val_size: 0.05
  dev_subsample_size: 200000
  min_per_subgroup_dev: 500
  toxic_threshold: 0.5
  identity_threshold: 0.5

identity_columns:
  - male
  - female
  - homosexual_gay_or_lesbian
  - christian
  - jewish
  - muslim
  - black
  - white
  - psychiatric_or_mental_illness

aux_columns:
  - severe_toxicity
  - obscene
  - threat
  - insult
  - identity_attack
  - sexual_explicit

transformer:
  model_name: microsoft/deberta-v3-base
  max_len: 220
  batch_size: 32
  eval_batch_size: 64
  lr: 2.0e-5
  warmup_ratio: 0.05
  epochs: 2
  weight_decay: 0.01
  fp16: true
  aux_loss_weight: 0.25
  use_multitask_heads: true   # flip to false + rerun for the ablation
  weighting_scheme: metric_derived   # none | inverse_frequency | metric_derived -- flip for the ablation table
  grad_accum_steps: 1
  max_grad_norm: 1.0
  log_every: 100
  checkpoint_every_steps: 2000
"""


def build_notebook() -> dict:
    cells = [
        md_cell(
"""# DeBERTa-v3 multi-task toxicity fine-tune -- Kaggle Notebook

Runs the exact same `src/` code developed and unit-tested locally
(this notebook just re-materializes those files here via `%%writefile`,
generated by `scripts/gen_kaggle_notebook.py` -- do not hand-edit the
code cells below, regenerate instead so this never drifts from what was
actually tested).

**Before running:**
1. Settings (right panel) -> Accelerator -> **GPU T4 x2** or **P100**.
2. Add data -> search **"Jigsaw Unintended Bias in Toxicity Classification"**
   -> Add. This mounts the competition files under
   `/kaggle/input/jigsaw-unintended-bias-in-toxicity-classification/`.
3. Settings -> Internet -> **On** (needed to download `deberta-v3-base`
   weights from Hugging Face on first run).
4. Session length: full-data training is ~3.5-4.5h/epoch x 2 epochs on a
   T4 -- comfortably inside a 9h session, but checkpoints are written
   every 2000 steps to `/kaggle/working/models/` in case of a disconnect.

**To run the ablations referenced in the README:** edit `config.yaml`
below (the `%%writefile config.yaml` cell) -- flip `use_multitask_heads`
and/or `weighting_scheme`, re-run that cell + the training cell, save a
new notebook version per configuration so each run's output is preserved.
"""
        ),
        md_cell("## 1. Install extra dependencies\n\n`torch`/`transformers` ship preinstalled on Kaggle GPU notebooks; this only adds what doesn't."),
        code_cell("!pip install -q sentencepiece pyyaml\n"),
        md_cell(
            "## 2. Materialize the project's src/ modules\n\n"
            "Identical content to the local repo's `src/metrics.py`, `src/data.py`, "
            "`src/model.py`, `src/train.py` -- see that repo for the documented "
            "rationale behind each design choice (bias metric derivation, "
            "weighting scheme, multi-task heads)."
        ),
        writefile_cell("metrics.py", read("metrics.py")),
        writefile_cell("data.py", read("data.py")),
        writefile_cell("model.py", read("model.py")),
        writefile_cell("train.py", read("train.py")),
        md_cell(
            "## 3. Kaggle-specific config\n\n"
            "Same hyperparameters as `config/config.yaml` in the repo; only the "
            "paths differ (point at `/kaggle/input/...` and write outputs under "
            "`/kaggle/working/`)."
        ),
        writefile_cell("config.yaml", KAGGLE_CONFIG),
        md_cell(
            "## 4. Smoke test (structural, ~1-2 min)\n\n"
            "Runs the full loop end-to-end on 300 rows before committing to a "
            "multi-hour run -- catches config/schema mistakes cheaply. Safe to "
            "skip once you've run it successfully once per notebook version."
        ),
        code_cell("!python train.py --config config.yaml --sample 300 --out-name smoketest\n"),
        md_cell(
            "## 5. Full training run\n\n"
            "This is the multi-hour cell. Metrics (overall AUC + the three bias "
            "power-means) print after every epoch; the final state_dict is saved "
            "to `/kaggle/working/models/deberta_multitask_final.pt` -- download "
            "it from the notebook's Output tab, or add `/kaggle/working` as a new "
            "Kaggle Dataset from the notebook's \"Save Version\" flow so it "
            "persists past the session."
        ),
        code_cell("!python train.py --config config.yaml --out-name deberta_multitask\n"),
        md_cell(
            "## 6. Copy results back into the local repo\n\n"
            "After downloading `/kaggle/working/reports/*.csv` from the Output "
            "tab, drop them into `reports/` locally and update the README's "
            "result tables + `reports/results.md` log."
        ),
    ]

    return {
        "cells": cells,
        "metadata": {
            "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
            "language_info": {"name": "python", "version": "3.10"},
            "accelerator": "GPU",
        },
        "nbformat": 4,
        "nbformat_minor": 5,
    }


if __name__ == "__main__":
    nb = build_notebook()
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(nb, indent=1), encoding="utf-8")
    print(f"wrote {OUT} ({len(nb['cells'])} cells)")
